projectName: PROJECTNAME
nameSpace: NAMESPACE

appType:
  frontend: webapp
  database: db
  api: api

replicaSet: 1
minReplicas: 1
maxReplicas: 1
averageCPUUtilization: 50
averageMemoryUtilization: 50

webappContainerService:
  type: ClusterIP
  port: 3000

katanaContainerService:
  type: ClusterIP
  port: 5050

toriiContainerService:
  type: ClusterIP
  port: 8080

grpcToriiContainerService:
  type: ClusterIP
  port: 50051


domainName: DOMAIN.TLD

subDomain: SUB

subDomainName:
  pixelaw: SUB
  katana: katana.SUB
  torii: torii.SUB
  grpcTorii: grpc.SUB

dockerImage: ghcr.io/pixelaw/core:latest

worldAddress: "WORLDADDRESS"

webApp:
  katanaUrl: "katanaUrl"
  toriiUrl: "toriiUrl"
  katanaSlotUrl: "katanaSlotUrl"
  toriiSlotUrl: "toriiSlotUrl"
  seed: "seed"
  totalAccounts: "totalAccounts"

