projectName: pixelaw-core
nameSpace: demo

appType:
  frontend: webapp
  database: db
  api: api

replicaSet: 1

minReplicas: 1
maxReplicas: 1
averageCPUUtilization: 50
averageMemoryUtilization: 50

webappContainerService:
  type: ClusterIP
  port: 3000

katanaContainerService:
  type: ClusterIP
  port: 5050

toriiContainerService:
  type: ClusterIP
  port: 8080

grpcToriiContainerService:
  type: ClusterIP
  port: 50051


domainName: pixelaw.xyz

subDomainName:
  pixelaw: demo
  katana: katana.demo
  torii: torii.demo
  grpcTorii: grpc.demo

dockerImage: ghcr.io/pixelaw/core:latest

worldAddress: "0x6395ccab8983e6598b8d54bac18cadb63d04b8e4631bde418a2cfb504b59a89"

webApp:
  katanaUrl: "https://api.cartridge.gg/x/pixelaw1/katana"
  toriiUrl: "https://api.cartridge.gg/x/pixelaw1/torii"
  katanaSlotUrl: "https://api.cartridge.gg/x/pixelaw1/katana"
  toriiSlotUrl: "https://api.cartridge.gg/x/pixelaw1/torii"
  seed: "7380699824140797174"
  totalAccounts: "4"
