---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.projectName }}-{{ .Values.nameSpace }}-{{ .Values.appType.frontend }}
  namespace: {{ .Values.projectName }}-{{ .Values.nameSpace }}
  labels:
    app: {{ .Values.projectName }}-{{ .Values.nameSpace }}-{{ .Values.appType.frontend }}
spec:
  replicas: {{ .Values.replicaSet }}
  selector:
    matchLabels:
      app: {{ .Values.projectName }}-{{ .Values.nameSpace }}-{{ .Values.appType.frontend }}
  template:
    metadata:
      labels:
        app: {{ .Values.projectName }}-{{ .Values.nameSpace }}-{{ .Values.appType.frontend }}
    spec:
      containers:
      - name: {{ .Values.projectName }}-{{ .Values.nameSpace }}-{{ .Values.appType.frontend }}
        image: {{ .Values.dockerImage }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.webappContainerService.port }}
        env:
          - name: PUBLIC_NODE_URL
            value: {{ .Values.webapp.katanaUrl }}
          - name: PUBLIC_TORII
            value: {{ .Values.webapp.toriiUrl }}
          - name: SLOT_KATANA
            value: {{ .Values.webapp.katanaSlotUrl }}
          - name: SLOT_TORII
            value: {{ .Values.webapp.toriiSlotUrl }}
          - name: SEED
            value: {{ .Values.webapp.seed }}
          - name: TOTAL_ACCOUNTS
            value: {{ .Values.webapp.totalAccounts }}
          - name: WORLD_ADDRESS
            value: {{ .Values.worldAddress }}

        # resources:
        #   requests:
        #     memory: "512Mi"
        #     cpu: "500m"
        #   limits:
        #     memory: "1Gi"
        #     cpu: "1000m"
        volumeMounts:
        - name: keiko-manifests
          mountPath: /keiko/manifests

      volumes:

      - name: keiko-manifests
        persistentVolumeClaim:
          claimName: pixelaw-core-{{ .Values.nameSpace }}-pvc
