apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.projectName }}-{{ .Values.nameSpace }}-pvc
  namespace: {{ .Values.projectName }}-{{ .Values.nameSpace }}
spec:
  storageClassName: do-block-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
